#!/bin/sh

# FORK copyright

# Copyright 2008 2009 2010 Douglas Wikstrom

# This file is part of Vfork.

# Vfork is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Vfork is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with Vfork.  If not, see
# <http://www.gnu.org/licenses/>.

DESTINATION=$1

vmni -prot \
-sid "SID" \
-name "Swedish Election" \
-nopart 3 \
-thres 2 \
-maxciph 10000 \
-pgroup "$(vog -gen ModPGroup -fixed 512)" \
${DESTINATION}/stub.xml

for i in 1 2 3
do
    vmni -party -name "Party$i" -hint mybox$i.mydomain$i.com:4040 -http http://mybox$i.mydomain$i.com:8080 ${DESTINATION}/stub.xml ${DESTINATION}/privInfo$i.xml ${DESTINATION}/protInfo$i.xml
done

vmni -merge ${DESTINATION}/protInfo*.xml ${DESTINATION}/protInfo.xml
