#!/bin/sh

# Copyright 2008 2009 2010 Douglas Wikstrom

# This file is part of Verificatum.

# Verificatum is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Verificatum is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with Verificatum.  If not, see
# <http://www.gnu.org/licenses/>.


SETUP_ENV='. ~/.verificatum_env'
TIME_FILE=timings_of_demo_secs
DATE_BIN=/bin/date
DEFAULT_PREFIX=mydemodir
MIXSERVER_HOSTS_1=fast.homeunix.org
USERNAME_1=dog
MIXSERVER_HOSTS_2=pitbull.csc.kth.se
USERNAME_2=dog
MIXSERVER_HOSTS_3=pitbull.csc.kth.se
USERNAME_3=dog

PGROUP_TYPE=rand_sg

INTER=native

KEY_DESTINATION=publicKey
TMP_COMMAND=./tmp_command
TMP_FILE=./tmp_file

SLEEPTIME=0

CORRECTNESS=noninteractive
ARRAYS=file



dump_params() {

    rm -f ${1}
    echo "SETUP_ENV='${SETUP_ENV}'" >> ${1}
    echo "TIME_FILE=${TIME_FILE}" >> ${1}
    echo "DATE_BIN=${DATE_BIN}" >> ${1}
    echo "DEFAULT_PREFIX=${DEFAULT_PREFIX}" >> ${1}
    echo "MIXSERVER_HOSTS_1=${MIXSERVER_HOSTS_1}" >> ${1}
    echo "USERNAME_1=${USERNAME_1}" >> ${1}
    echo "MIXSERVER_HOSTS_2=${MIXSERVER_HOSTS_2}" >> ${1}
    echo "USERNAME_2=${USERNAME_2}" >> ${1}
    echo "MIXSERVER_HOSTS_3=${MIXSERVER_HOSTS_3}" >> ${1}
    echo "USERNAME_3=${USERNAME_3}" >> ${1}
    echo "PGROUP_TYPE=${PGROUP_TYPE}" >> ${1}
    echo "SUBSCH=${SUBSCH}" >> ${1}
    echo "SLEEPTIME=${SLEEPTIME}" >> ${1}
    echo "KEY_DESTINATION=${KEY_DESTINATION}" >> ${1}
    echo "TMP_COMMAND=${TMP_COMMAND}" >> ${1}
    echo "TMP_FILE=${TMP_FILE}" >> ${1}
    echo "CORRECTNESS=${CORRECTNESS}" >> ${1}
    echo "INTER=${INTER}" >> ${1}
    echo "ARRAYS=${ARRAYS}" >> ${1}
    echo "NO_MIXSERVERS=${NO_MIXSERVERS}" >> ${1}
    echo "MAX_NO_CIPHERTEXTS=${MAX_NO_CIPHERTEXTS}" >> ${1}
    echo "NO_CIPHERTEXTS=${NO_CIPHERTEXTS}" >> ${1}
    echo "BIT_SIZE=${BIT_SIZE}" >> ${1}
    echo "OBIT_SIZE=${OBIT_SIZE}" >> ${1}

    echo ". ./macros" >> ${1}

}


MULTIPLIER=100

for BIT_SIZE in 1024 2048;
do
    for NO_MIXSERVERS in 3 5 7;
    do
	for MAX_NO_KCIPHERTEXTS in 10 20 40 80 160;
	do

	    MAX_NO_CIPHERTEXTS=$(( $MULTIPLIER * $MAX_NO_KCIPHERTEXTS ))
	    OBIT_SIZE=$(( $BIT_SIZE - 5 ))
	    NO_CIPHERTEXTS=${MAX_NO_CIPHERTEXTS}

	    rm -f $TIME_FILE
	    dump_params conf

	    ./demo

	    cat $TIME_FILE > timing_${CORRECTNESS}_${ARRAYS}_M${NO_MIXSERVERS}_K${BIT_SIZE}_C${NO_CIPHERTEXTS}

	    ./clean

	done
    done
done
