#!/bin/sh

# Copyright 2008 2009 2010 Douglas Wikstrom

# This file is part of Vfork.

# Vfork is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Vfork is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with Vfork.  If not, see
# <http://www.gnu.org/licenses/>.


###########################################################################
################### Execute standalone verifier. ##########################
###########################################################################

. ./conf

if test $CORRECTNESS = "noninteractive"
then

    vmnv -v -e -wd "/tmp/vfork/$$" -a $ARRAYS export/protInfo.xml export/roProof/ export/${KEY_DESTINATION} export/ciphertexts export/plaintexts
    EXIT_STATUS=$?
    rm -rf "/tmp/vfork/$$"
    exit ${EXIT_STATUS}
else

    echo ""
    echo "ERROR!"
    echo "You can not verify an execution that used *interactive* "
    echo "zero-knowledge proofs. Please edit the CORRECTNESS variable"
    echo "in the conf-file to try out *non-interactive* proofs in the"
    echo "random oracle model."
    echo ""

fi