#!/bin/sh

# Copyright 2008 2009 2010 Douglas Wikstrom

# This file is part of Vfork.

# Vfork is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Vfork is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with Vfork.  If not, see
# <http://www.gnu.org/licenses/>.


# This script assumes that check_CLASSPATH succeeded.

java mixnet.ui.gen.GeneratorTool > /dev/null 2> .check_output
LD=`cat .check_output | grep UnsatisfiedLinkError`
rm -f .check_output
if test "x${LD}" != x;
then
    echo \
"

ERROR! When using native code, your LD_LIBRARY_PATH environment
variable must point to the directory containing the native code
library libgmpmee.a.

"
    exit 1
else
    echo "LD_LIBRARY_PATH is correctly configured."
fi
