#!/bin/sh

# Copyright 2008 2009 2010 Douglas Wikstrom

# This file is part of Vfork.

# Vfork is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Vfork is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with Vfork.  If not, see
# <http://www.gnu.org/licenses/>.

vog -gen PRGHeuristic > .check_output 2> /dev/null 

RES=`cat .check_output | grep PRGHeuristic`
rm -f .check_output
if test "x${RES}" = x;
then
    echo \
"

ERROR! Your PATH environment variable must contain the location of the
installed executables, e.g., vog, vmni, and vmn.

"
    exit 1
else
    echo "PATH is correctly configured."
fi
