#!/bin/sh

# Copyright 2008 2009 2010 Douglas Wikstrom

# This file is part of Vfork.

# Vfork is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Vfork is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with Vfork.  If not, see
# <http://www.gnu.org/licenses/>.



PROTOCOLS="\
vfork.protocol.distrkeygen.DemoPlainKeys \
vfork.protocol.secretsharing.DemoPedersen \
vfork.protocol.secretsharing.DemoPedersenSequential \
vfork.protocol.coinflip.DemoCoinFlipPRingSource \
vfork.protocol.hvzk.DemoSigmaProof \
vfork.protocol.hvzk.DemoSigmaProofSequential \
vfork.protocol.hvzk.DemoPoSTW \
vfork.protocol.distrkeygen.DemoIndependentGenerator \
vfork.protocol.distrkeygen.DemoIndependentGeneratorsI \
vfork.protocol.distrkeygen.DemoDKG"

#PROTOCOLS=vfork.protocol.distrkeygen.DemoPlainKeys
#PROTOCOLS=vfork.protocol.secretsharing.DemoPedersen
#PROTOCOLS=vfork.protocol.secretsharing.DemoPedersenSequential
#PROTOCOLS=vfork.protocol.coinflip.DemoCoinFlipPRingSource
#PROTOCOLS=vfork.protocol.hvzk.DemoSigmaProof
#PROTOCOLS=vfork.protocol.hvzk.DemoSigmaProofSequential
#PROTOCOLS=vfork.protocol.hvzk.DemoPoSTW
#PROTOCOLS=vfork.protocol.hvzk.DemoPoSTWSequential
#PROTOCOLS=vfork.protocol.distrkeygen.DemoIndependentGenerator
#PROTOCOLS=vfork.protocol.distrkeygen.DemoIndependentGeneratorsI
#PROTOCOLS=vfork.protocol.distrkeygen.DemoDKG


for prot in `echo $PROTOCOLS`;
do

java \
-Djava.security.egd=file:/dev/./urandom \
-Djavax.accessibility.assistive_technologies=java.lang.String \
$prot -g -nopart 3 -thres 2 demodir_$prot

java \
-Djava.security.egd=file:/dev/./urandom \
-Djavax.accessibility.assistive_technologies=java.lang.String \
$prot -e -close demodir_$prot

#-Xms1024m -Xmx2048m \
#-Xms1024m -Xmx2048m \
# java \
# -Xms1024m -Xmx2048m \
# -Djava.security.egd=file:/dev/./urandom \
# -Djavax.accessibility.assistive_technologies=java.lang.String \
# $prot -e -close demodir_$prot

done

